- hosts: deploy-vwa-hackazon
  sudo: yes
  tasks:
   - name: Check kernel version.
     fail: msg="Kernel {{ ansible_kernel }} is not supported."
     when: "ansible_kernel | version_compare('3.10', '<')"

   - name: apt-get install packages
     apt: pkg={{ item }} state=present update_cache=yes
     with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - linux-image-extra-virtual
       - linux-image-extra-{{ ansible_kernel }}
       - software-properties-common

   - name: Check docker gpg key.
     shell: apt-key fingerprint 0EBFCD88 | grep 0EBFCD88
     register: docker_gpg
     ignore_errors: True
     changed_when: False

   - name: Add Docker’s official GPG key
     shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
     when: docker_gpg | failed

   - name: define lsb_release -cs
     shell: lsb_release -cs
     ignore_errors: True
     register: lsb_release

   - name: set up the stable repository
     shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"

   - name: Install docker-ce.
     apt: name=docker-ce state=present update_cache=yes
     notify:
       - restart docker

   - name: Check if Docker-Compose exists
     stat: path=/usr/local/bin/docker-compose
     register: dc

   - name: Install Docker-Compose
     shell: curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
     when: not dc.stat.exists
