- hosts: deploy-vwa-hackazon
  sudo: yes
  tasks:
    - name: "downloading docker file"
      unarchive: 
         src: "https://github.com/cmutzel/all-in-one-hackazon/archive/master.zip"
         dest: /tmp
         remote_src: True
    - name: "setting hackazon"
      replace: >
         dest=/tmp/all-in-one-hackazon-master/Dockerfile
         regexp='ubuntu:latest'
         replace='ubuntu:14.04'
    - name: "setting hackazon"
      replace: >
         dest=/tmp/all-in-one-hackazon-master/Dockerfile
         regexp='\["/bin/bash", "/start.sh"\]'
         replace='["/bin/bash"]'
    - name: "build hackazon"
      shell: docker build -t="image/hackazon" /tmp/all-in-one-hackazon-master
    - name: "start hackazon"
      shell: docker run -d --name hackazon -it -p 80:80 image/hackazon
